### ISSUE TITLE
dependencies triggering potential security vulnerabilities warnings from github

### ISSUE THREAD

**Issue by malexanderboyd** [malexanderboyd/ThreatBOOM#1]
The following dependencies are triggering security vulnerabilities. These should be updated so they no longer trigger github's warnings.

```

hapijs / cryptiles

hapijs / hoek

lodash / lodash

scravy / node-macaddress macaddress

broofa / node-mime mime

joyent / node-sshpk sshpk

unshiftio / url-parse
```

**Comment by TiagoDanin** [comment]
@malexanderboyd I use [snyk.io](https://snyk.io/) to fix the lodash and other dependencies.
